# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96bae870c48a030aebfbfea6095818823e1ba56dfb1bf2b4b7a7f15a3c278f4849a936d8a8124fbfed875900ef3932fac2aefb5f46f8056495c6e676fa5e296f

test:
  secret_key_base: 2cc1d14516e0febb34067e6777cc1c5a979e168fb30b985f9df32ed6ca226d90ce03edeec8432f9ce6e86c02304d5b1a8ef118efcc06ef659f6280255a772785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
